config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "static_pages/home", to: "static_pages#home"
  get "static_pages/adminpage", to: "static_pages#adminpage"
  get 'search_hotels/show', to: "search_hotels#show"
  get "auth/:provider/callback", to: "sessions#create_from_socialmedia"
  get '/redirect', to: 'example#redirect', as: 'redirect'
  get '/callback', to: 'example#callback', as: 'callback'
  get '/calendars', to: 'example#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'example#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'example#new_event', as: 'new_event', calendar_id: /[^\/]+/
  get 'auth/failure', to: redirect('/')

  resources :users, only: [:new, :create]

  namespace :admin do
    resources :hotels
    resources :cities
    resources :rooms
  end

  resources :galleries, only: [:new, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :search_hotels, only: :show
  resources :bookings do
    get :client_bookings, on: :collection
    get :update_status, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_auth
  before_action :authenticate_user! => nil, only: [:adminpage]
  before_action :authenticate_admin!, only: [:adminpage]

  def home
    @hotels = Hotel.all
    @search = if params[:search].present?
      JSON.parse(params[:search].to_s.gsub('=>', ':')).except!(["utf8", "commit", "controller", "action"])
    else
      {"num_of_guests" => nil, "num_of_rooms" => nil, "check_in_date" => nil, "check_out_date" => nil, "city"  => nil}
    end
  end

  def adminpage
  end

  private
  def set_auth
    @auth = session[:omniauth] if session[:omniauth]
  end

end

app/views/static_pages/adminpage.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <%= image_tag("room.jpeg", alt: "room") %><br>
      <%= link_to "View Rooms", admin_rooms_path, class: "nav-link" %>
    </div>
    <div class="col-sm-4">
      <%= image_tag("hotel.jpeg", alt: "hotel") %><br>
      <%= link_to "View Hotels", admin_hotels_path, class: "nav-link" %>
    </div>
    <div class="col-sm-4">
      <%= image_tag("city.jpeg", alt: "city") %><br>
      <%= link_to "View Cities", admin_cities_path, class: "nav-link" %>
    </div>
    <div class="col-sm-4">
      <%= image_tag("city.jpeg", alt: "Gallery") %><br>
      <%= link_to "View Galleries", new_gallery_path, class: "nav-link" %>
    </div>
    <div class="col-sm-4">
      <%= image_tag("room.jpeg", alt: "Booking") %><br>
      <%= link_to "View Bookings", bookings_path, class: "nav-link" %>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">

      <div class="center hero-unit">

        <div id="demo" class="carousel slide" data-ride="carousel">

          <!-- Indicators -->
          <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
          </ul>

          <!-- The slideshow -->
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= image_tag("a.jpg", alt: "hotel 1") %>
              <div class="carousel-caption">
                <h1> WELCOME TO HOTEL RESERVATION SYSTEM</h1>
                <h3>Chicago</h3>
                <p>Thank you, Chicago!</p>
              </div>
            </div>

            <div class="carousel-item">
              <%= image_tag("b.jpg", alt: "hotel 2") %>
              <div class="carousel-caption">
                <h1> WELCOME TO HOTEL RESERVATION SYSTEM</h1>
                <h3>Los Angeles</h3>
                <p>LA is always so much fun!</p>
              </div>
            </div>

            <div class="carousel-item">
              <%= image_tag("c.jpg", alt: "hotel 3") %>
              <div class="carousel-caption">
                <h1> WELCOME TO HOTEL RESERVATION SYSTEM</h1>
                <h3>New York</h3>
                <p>We love the Big Apple!</p>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
    <div class="col-md-6">
      <div class="container">
        <div class="row">
          <div class="col-md-12 min-vh-100 d-flex flex-column justify-content-center">
            <div class="row">
              <div class="col-lg-8 col-md-6 mx-auto">

                <!-- form card login -->
                <div class="card rounded shadow shadow-sm">
                  <div class="card-header">
                    <h3 class="mb-0">Search Filters</h3>
                  </div>
                  <div class="card-body">
                    <%= form_tag search_hotels_show_path, method: :get do %>
                    <div class = "form-group">
                      <%= label_tag :num_of_guests, "No of Guests" %>
                      <%= number_field_tag :num_of_guests, @search['num_of_guests']  %>
                    </div>
                    <div class = "form-group">
                      <%= label_tag :num_of_rooms, "No of Rooms "%>
                      <%= number_field_tag :num_of_rooms, @search['num_of_rooms'] %>
                    </div>
                    <div class = "form-group">
                      <%= label_tag :check_in_date, "Check IN "%>
                      <%= date_field_tag :check_in_date, @search['check_in_date'] %>
                    </div>
                    <div class = "form-group">
                      <%= label_tag :check_out_date, "Check Out "%>
                      <%= date_field_tag :check_out_date, @search['check_out_date'] %>
                    </div>
                    <div class ="form-group">
                      <%= label_tag :city, "city"%>
                      <%= select_tag "city", options_from_collection_for_select(City.all, "id", "name", @search['check_out_date'].present? ? @search['check_out_date'] : 1 )%>
                    </div>
                    <div class = "form-group">
                      <%= submit_tag "SUBMIT", value: params[:num_of_guests], class: "btn btn-primary" %>
                    </div>
                    <% end %>
                  </div>
                  <!--/card-block-->
                </div>
                <!-- /form card login -->
              </div>
            </div>
            <!--/row-->
          </div>
          <!--/col-->
        </div>
        <!--/row-->
      </div>
    </div>

    <%= render(partial: "search_hotels/ListHotels") %>