config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "static_pages/home", to: "static_pages#home"
  get "static_pages/adminpage", to: "static_pages#adminpage"
  get 'search_hotels/show', to: "search_hotels#show"
  get "auth/:provider/callback", to: "sessions#create_from_socialmedia"
  get '/redirect', to: 'example#redirect', as: 'redirect'
  get '/callback', to: 'example#callback', as: 'callback'
  get '/calendars', to: 'example#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'example#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'example#new_event', as: 'new_event', calendar_id: /[^\/]+/
  get 'auth/failure', to: redirect('/')

  resources :users, only: [:new, :create]

  namespace :admin do
    resources :hotels
    resources :cities
    resources :rooms
  end

  resources :galleries, only: [:new, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :search_hotels, only: :show
  resources :bookings do
    get :client_bookings, on: :collection
    get :update_status, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :hotel
  belongs_to :user

  enum status: %w(pending approved rejected)

  validates :num_of_guests, :guest_name, :check_in_date, :check_out_date,  presence: true
  validate :check_out_greater_than_check_in
  validates_associated :hotel, :user

  def check_out_greater_than_check_in

    if check_in_date.present? && check_in_date > check_out_date
      errors.add(:check_out_date, "Cant be lesser than check in!")
    end
  end

  def alter_rooms_booked(hotel)
    single    = hotel.single_bedroom_num.to_i
    double    = hotel.double_bedroom_num.to_i
    suite     = hotel.suite_room_num.to_i
    dormitory = hotel.dormitory_room_num.to_i
    s_new     = self.single_bedroom_num.to_i
    d_new     = self.double_bedroom_num.to_i
    sui_new   = self.suite_room_num.to_i
    dor_new   = self.dormitory_room_num.to_i
    h_id      = self.hotel_id.to_i
    s_res     = (single - s_new)
    d_res     = (double - d_new)
    sui_res   = (suite - sui_new)
    dor_res   = (dormitory - dor_new)
    hotel.update_attributes(single_bedroom_num: s_res, double_bedroom_num: d_res, suite_room_num: sui_res, dormitory_room_num: dor_res )
  end

  def total_price_of_booking(hotel)
    single          = single_bedroom_num.to_i
    double          = double_bedroom_num.to_i
    suite           = suite_room_num.to_i
    dormitory       = dormitory_room_num.to_i
    single_price    = hotel.single_bedroom_price.to_i
    double_price    = hotel.double_bedroom_price.to_i
    suite_price     = hotel.suite_room_price.to_i
    dormitory_price = hotel.dormitory_room_price.to_i
    total_price     = (single * single_price) + (double * double_price) + (suite * suite_price) + (dormitory * dormitory_price)
    self.update_attributes(total: total_price)
  end


# Using cronjob to call release_rooms method every day at 11:30a.m (config/schedule.rb) in production evironment.
def self.release_rooms

  all.each do |booking|

    if booking.check_out_date <= Date.today

      single = booking.hotel.single_bedroom_num.to_i
      double = booking.hotel.double_bedroom_num.to_i
      suite = booking.hotel.suite_room_num.to_i
      dormitory = booking.hotel.dormitory_room_num.to_i
      s_new = booking.single_bedroom_num.to_i
      d_new = booking.double_bedroom_num.to_i
      sui_new = booking.suite_room_num.to_i
      dor_new = booking.dormitory_room_num.to_i
      s_res = (single + s_new)
      d_res = (double + d_new)
      sui_res = (suite + sui_new)
      dor_res = (dormitory + dor_new)
      @hotel = booking.hotel
      @hotel.update_attributes(single_bedroom_num: s_res, double_bedroom_num: d_res, suite_room_num: sui_res, dormitory_room_num: dor_res )
    end
  end
end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!, only: [:client_bookings, :update_status]
  before_action :get_booking, only: [:update_status, :destroy]
  def index
    bookings = []
    reservations = current_user.admin? ? Booking.all : Booking.where(user_id: current_user.id)
    reservations.each do |booking|
      bookings << {id: booking.id, title: "#{booking.guest_name}  #{!booking.approved? ? 'event is '+booking.status.titleize : ''  }", start: booking.check_in_date, end: booking.check_out_date + 1.day} if booking.check_in_date.present?
    end
    gon.bookings = bookings
  end

  def new
    @booking = Booking.new
    session[:hotel_id] = params[:hotel_id]
    @hotel     = current_hotel
    @single    = @hotel.single_bedroom_num.to_i
    @double    = @hotel.double_bedroom_num.to_i
    @suite     = @hotel.suite_room_num.to_i
    @dormitory = @hotel.dormitory_room_num.to_i
  end

  def create
    authorize unless signed_in?
    @booking  = current_hotel.bookings.build(book_params)
    @booking.user_id = current_user.id
    if @booking.save
      ConfirmMailer.inform_email(current_user, @booking).deliver
      AdminMailMailer.admin_email(User.admin, current_user, @booking).deliver
      alter_rooms(current_hotel)
      redirect_to bookings_path, flash: { success: "Booked successfully!" }
    else
      flash.now[:error] = "Couldn't make the booking."
    end
  end

  def client_bookings
    @bookings = Booking.all
  end

  def update_status
    @booking.update(status: params[:status])
    if @booking.rejected?
      rewise_room_hotel(@booking)
      ConfirmMailer.rejected_email(current_user, @booking).deliver
    elsif @booking.approved?
      ConfirmMailer.approved_email(current_user, @booking).deliver
    end
    redirect_to(action: :client_bookings)
  end


  def destroy
    rewise_room_hotel(@booking)
    @booking.destroy
    redirect_to(action: :client_bookings)
  end

  private

  def book_params
    params.require(:booking).permit(:id, :num_of_guests, :guest_name, :check_in_date, :check_out_date, :single_bedroom_num, :double_bedroom_num, :suite_room_num, :dormitory_room_num, :user_id)
  end
  def current_hotel
    @current_hotel ||= Hotel.find(session[:hotel_id])
  end

  def alter_rooms(hotel)
    @booking.alter_rooms_booked(hotel)
    @booking.total_price_of_booking(hotel)
  end

  def get_booking
    @booking = Booking.find(params[:id])
  end

  def rewise_room_hotel(booking)
    hotel = booking.hotel
    hotel.single_bedroom_num += booking.single_bedroom_num
    hotel.double_bedroom_num += booking.double_bedroom_num
    hotel.suite_room_num     += booking.suite_room_num
    hotel.dormitory_room_num += booking.dormitory_room_num
    hotel.save
  end

  # def set_null_booking(booking)
  #   booking.udpate(single_bedroom_num: 0,double_bedroom_num: 0,suite_room_num: 0,dormitory_room_num: 0)
  # end


end

app/views/bookings/client_bookings.html.erb
<table class="listing" summary="city list">
  <thead class="thead-dark">
    <tr class = "header">
      <th>Id</th>
      <th>Name</th>
      <th>Check In </th>
      <th>Check Out</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
    <tr>
      <td><%= booking.id %> |</td>
      <td><%= booking.guest_name %> |</td>
      <td><%= booking.check_in_date %> | </td>
      <td><%= booking.check_out_date %> |</td>
      <td><%= booking.status.titleize %> | </td>
      <td class = "actions">
        <%= link_to('Click to Approved |', update_status_booking_path(booking, status: :approved), class: "action show") if booking.rejected? || booking.pending? %>
        <%= link_to('Click to Rejected |', update_status_booking_path(booking, status: :rejected), class: "action show") if booking.approved? || booking.pending? %>
        <%= link_to("Click to DELETE", booking_path(booking), data: {confirm: "ARE YOU SURE?"}, method: :delete, class: "action delete") %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/index.html.erb
<%if current_user.admin?%>
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Bookings</h1>
      <p>
        <%= link_to("Back ", static_pages_adminpage_path, class: "btn btn-primary my-2") %>
        <%= link_to "Approve and Reject bookings", client_bookings_bookings_path, class: "btn btn-primary my-2" %>
      </p>
    </div>
  </section>
<% end %>

<header class="header" id="myHeader">
  <h1>Reservation Calendar</h1>
</header>
<div class="content-holder">
  <div id="calendar">
  </div>
</div>
<div id="event-modal"></div>

app/views/bookings/new.html.erb
<% @page_title = "Booking Page" %>
<div class="container">
<div class="row">
<div class="col-md-12 min-vh-100 d-flex flex-column justify-content-center">
<div class="row">
<div class="col-lg-6 col-md-8 mx-auto">

<!-- form card login -->
<div class="card rounded shadow shadow-sm">
<div class="card-header">
<h3 class="mb-0">Booking Page</h3>
</div>
<div class="card-body">

<%= form_for @booking do |f| %>
  <%= render(partial: "error_refer/error", locals: { target: @booking }) %>
  <ul class = "list-group">
    <% @errors.try(:each) do |message| %>
      <li class = "list-group-item">  <%= message %></li>
    <% end %>
  </ul>

  <div class = "form-group">
      <%= f.label :guest_name, "Name of Guest"%>
      <%= f.text_field :guest_name, placeholder: "Enter your name", class: "form-control" %>
  </div>

  <div class = "form-group">
      <%= f.label :check_in_date, "Check IN "%>
      <%= f.date_field :check_in_date, min: Date.today, placeholder: "Enter check in date", class: "form-control" %>
  </div>

  <div class = "form-group">
    <%= f.label :check_out_date, "Check Out "%>
    <%= f.date_field :check_out_date, min: Date.today, placeholder: "Enter check out date", class: "form-control" %>
  </div>

  <div class = "form-group">
    <%= f.label :no_of_guests, "No. of Guests" %>
    <%= f.number_field :num_of_guests, min: 0, max: 10 %>
  </div>
  <% unless @single.zero? %>
    <div class = "form-group">
      <%= f.label :single_bedroom_num, "No. of Single bedrooms" %>
      <%= f.number_field :single_bedroom_num, min: 0, max: @single %>
    </div>
  <% end %>

  <% unless @double.zero? %>
    <div class = "form-group">
      <%= f.label :double_bedroom_num, "No. of Double bedrooms "%>
      <%= f.number_field :double_bedroom_num, min: 0, max: @double %>
    </div>
  <% end %>

  <% unless @suite.zero? %>
    <div class = "form-group">
      <%= f.label :suite_room_num, "No. of suite rooms "%>
      <%= f.number_field :suite_room_num, min: 0, max: @suite %>
    </div>
  <% end %>


  <% unless @dormitory.zero? %>
    <div class = "form-group">
      <%= f.label :dormitory_room_num, "No. of dormitory rooms "%>
      <%= f.number_field :dormitory_room_num, min: 0, max: @dormitory%>
    </div>
  <% end %>


    <div class = "form-group">
      <%= f.hidden_field :hotel_id, value: params[:hotel_id] %>
    </div>

  <div class = "form-group">
    <%= f.hidden_field :hotel_name, value: params[:hotel_name] %>
  </div>


  <div class = "form-group">
    <%= f.submit "SUBMIT", class: "btn btn-primary" %>
  </div>
<% end %>
</div>
<!--/card-block-->
</div>
<!-- /form card login -->
</div>
</div>
<!--/row-->
</div>
<!--/col-->
</div>
<!--/row-->
</div>
<!--/container-->

app/views/bookings/reservations.html.erb
<header class="header" id="myHeader">
  <h1>Reservation Calendar</h1>
</header>
<div class="content-holder">
  <div id="calendar">
  </div>
</div>
<div id="event-modal"></div>