config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "static_pages/home", to: "static_pages#home"
  get "static_pages/adminpage", to: "static_pages#adminpage"
  get 'search_hotels/show', to: "search_hotels#show"
  get "auth/:provider/callback", to: "sessions#create_from_socialmedia"
  get '/redirect', to: 'example#redirect', as: 'redirect'
  get '/callback', to: 'example#callback', as: 'callback'
  get '/calendars', to: 'example#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'example#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'example#new_event', as: 'new_event', calendar_id: /[^\/]+/
  get 'auth/failure', to: redirect('/')

  resources :users, only: [:new, :create]

  namespace :admin do
    resources :hotels
    resources :cities
    resources :rooms
  end

  resources :galleries, only: [:new, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :search_hotels, only: :show
  resources :bookings do
    get :client_bookings, on: :collection
    get :update_status, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	has_many :bookings
	belongs_to :city
	validates_associated :city

	geocoded_by :address
	after_validation :geocode

	validates :name, :address, presence: true, uniqueness: true
	validates :single_bedroom_price, :double_bedroom_price, :suite_room_price, :dormitory_room_price,
					  :single_bedroom_num, :double_bedroom_num, :suite_room_num, :dormitory_room_num,
					  presence: true

	has_attached_file :picture, styles: {large: "500x500>", medium: "300x300>", thumb: "150x150#"}
	validates_attachment_content_type :picture, content_type: %r{\Aimage\/.*\z}
	validates_attachment_presence :picture

	# IMAGE_TYPES = %w[image/gif image/jpeg image/pjpeg image/x-png image/png].freeze

	# has_one_attached :image

	# validates :image, content_type: { in: IMAGE_TYPES, message: 'invalid format' }, requisites: false

	# def image_path
	#   image.attached? ? image : 'account-add-photo.svg'
	# end

end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < Admin::BaseController
  before_action :find_hotel, only: [:edit, :update, :destroy, :show]

  def new
    @hotel  = Hotel.new
    prior_data
  end

  def index
    @hotels = Hotel.all
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save
      redirect_to admin_hotel_path(@hotel)
    else
      prior_data
      render :new, flash: { error: "Invalid data entry" }
    end
  end

  def update
    if @hotel.update_attributes(hotel_params)
      redirect_to admin_hotel_path
    else
      prior_data
      render :edit, flash: { error: "Validation error" }
    end
  end

  def edit
    prior_data
  end

  def destroy
    @hotel.destroy
    redirect_to(action: "index")
  end

  private

  def hotel_params
    params.require(:hotel).permit(:name, :city_id, :picture, :address, :single_bedroom_price, :double_bedroom_price, :suite_room_price, :dormitory_room_price, :single_bedroom_num, :double_bedroom_num, :suite_room_num, :dormitory_room_num)
  end

  def find_hotel
    @hotel = Hotel.find(params[:id])
  end

  def prior_data
    @cities = City.all
  end

end

app/views/admin/hotels/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 min-vh-60 d-flex flex-column justify-content-center">
      <div class="row">
        <div class="col-lg-12">
          <!-- form card  -->
          <div class="card rounded shadow shadow-sm">
            <div class="card-header">
              <h3 class="mb-0">Hotel</h3>
            </div>
            <div class="card-body">
              <%= form_for [:admin, @hotel] do |f| %>
              <%= render(partial: "error_refer/error", locals: { target: @hotel }) %>

              <div class = "form-group">
                <%= f.label :name, "Name of Hotel "%>
                <%= f.text_field :name, placeholder: "Enter your name", class: "form-control", step: 0.1, min: 0, required: true %>
              </div>

              <div class ="form-group">
                <%= f.label :city, "Select City"%>
                <%= f.select :city_id, @cities.map { |type| [type.name.titleize, type.id] },{ include_hidden: false }, class: 'form-control', required: true %>
              </div>

              <div class ="form-group">
                <%= f.label :address, "Address of Hotel"%>
                <%= f.text_field :address, placeholder: "address", class: "form-control", step: 0.1, min: 0, required: true %>
              </div>

              <div class = "form-group">
                <%= f.label :single_bedroom_price, "Single bedroom price:"%>
                <%= f.number_field :single_bedroom_price, placeholder: "Enter price per room", class: "form-control", step: 0.1, min: 0.0 %>
              </div>

              <div class = "form-group">
                <%= f.label :double_bedroom_price, "Double bedroom price:"%>
                <%= f.number_field :double_bedroom_price, placeholder: "Enter price per room", class: "form-control", step: 0.1, min: 0.0 %>
              </div>

              <div class = "form-group">
                <%= f.label :suite_room_price, "Suite room price :"%>
                <%= f.number_field :suite_room_price, placeholder: "Enter price per room", class: "form-control", step: 0.1, min: 0.0 %>
              </div>

              <div class = "form-group">
                <%= f.label :dormitory_room_price, "Dormitory room price :"%>
                <%= f.number_field :dormitory_room_price, placeholder: "Enter price per room", class: "form-control", step: 0.1, min: 0.0 %>
              </div>-

              <div class = "form-group">
                <%= f.label :single_bedroom_num, "No. of singlebed rooms:"%>
                <%= f.number_field :single_bedroom_num, placeholder: "Enter availability", class: "form-control", step: 1, min: 0 %>
              </div>

              <div class = "form-group">
                <%= f.label :double_bedroom_num, "No. of double bedroom_num rooms:"%>
                <%= f.number_field :double_bedroom_num, placeholder: "Enter availability", class: "form-control", step: 1, min: 0 %>
              </div>

              <div class = "form-group">
                <%= f.label :suite_room_num, "No. of suite room num rooms:"%>
                <%= f.number_field :suite_room_num, placeholder: "Enter availability", class: "form-control", step: 1, min: 0 %>
              </div>

              <div class = "form-group">
                <%= f.label :dormitory_room_num, "No. of dormitory room num rooms:"%>
                <%= f.number_field :dormitory_room_num, placeholder: "Enter availability", class: "form-control", step: 1, min: 0 %>
              </div>

              <div class="form-group">
                <label>Hotel Preview</label>
                <div class="dz-clickable media align-items-center" data-toggle="dropzone" data-dropzone-url="http://" data-dropzone-clickable=".dz-clickable" data-dropzone-files="[&quot;assets/images/account-add-photo.svg&quot;]">
                  <div class="dz-preview dz-file-preview dz-clickable mr-3">
                    <div class="avatar avatar-lg dz-error dz-complete">
                      <%= image_tag f.object.picture&.exists? ?  f.object&.picture.url : 'account-add-photo.svg',  class: 'avatar-img rounded', data: { 'dz-thumbnail' => '' } %>
                    </div>
                  </div>
                  <div class="media-body">
                    <%= f.file_field :picture, class: 'btn btn-sm dz-clickable' %>
                  </div>
                </div>
              </div>

              <div class = "form-group">
                <%= f.submit "Submit", class: "btn btn-primary" %>
              </div>

              <div class="container-border bg-white py-2 px-4 my-3">
                <div class="row">
                  <%= f.hidden_field :latitude %>
                  <%= f.hidden_field :longitude %>
                  <div id="hotel_map_marker"></div>
                </div>
              </div>

              <% end %>
            </div>
            <!--/card-block-->
          </div>
          <!-- /form card login -->
        </div>
      </div>
      <!--/row-->
    </div>
    <!--/col-->
  </div>
  <!--/row-->
</div>
<!--/container-->

app/views/admin/hotels/edit.html.erb
<h1>Hotels#edit</h1>
<%= link_to("<< Back to index list", {action: "index"}, class: "back_to_link") %>
<div class = "hotels ">
  <h2>Update hotels</h2>
    <%= render(partial: "form") %>
</div>

app/views/admin/hotels/index.html.erb
<div class="hotels index">
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Hotels</h1>
      <p class="lead text-muted">Best hotels curated for you.</p>
      <p>
        <%= link_to("Add New hotel", {action: "new"}, class: "action new btn btn-primary my-2") %>
        <%= link_to("Back to Home Page", root_path, class: "btn btn-primary my-2") %>
        <%= link_to "Admin Page", static_pages_adminpage_path, class: "btn btn-primary my-2" %>
      </p>
    </div>
  </section>

  <div class="container">
    <% @hotels.each_slice(3)  do |hotels| %>
    <div class="row">
      <% hotels.each  do |hotel| %>
      <div class="col-sm-6 col-lg-4">
        <div class="card" style="width: 18rem;">
          <%= image_tag(hotel.picture.url(:thumb), alt: "No hotel found") %>  <div class="card-body">
            <h6><%= hotel.name %></h6>
            <h6><%= hotel&.city&.name %></h6>
            <p class="card-text">
              <%= link_to("Show", admin_hotel_path(hotel), class: "action show") %>
              <%= link_to("Edit", edit_admin_hotel_path(hotel), class: "action edit") %>
              <%= link_to("Delete", admin_hotel_path(hotel), data: {confirm: "ARE YOU SURE?"}, method: :delete, class: "action delete") %>
            </p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>

app/views/admin/hotels/new.html.erb
<%= link_to("<< Back to index list", {action: "index"}, class: "back_to_link") %>
<div class = "hotels new">
  <h2>Admin Updates for Hotels</h2>
    <%= render(partial: "form") %>
</div>

app/views/admin/hotels/show.html.erb
<%= javascript_include_tag "application" %>
<%#= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+Rails.application.credentials.google_maps_api_key %>
  <% provide :head_tags do %>
   <meta name='turbolinks-visit-control' content='reload'>
   <script>
     document.addEventListener("DOMContentLoaded", function(){
       initMap(<%=@hotel.latitude%>, <%=@hotel.longitude%>)
     });
   </script>
  <% end %>
<%= link_to("<< Back to index list", {action: "index"}, class: "back_to_link") %>
<div class = "hotels show">
  <h2>Show hotel details</h2>
  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Hotel Name</th>
        <th scope="col">City</th>
        <th scope="col">Singleroom</th>
        <th scope="col">Doubleroom</th>
        <th scope="col">Suite</th>
        <th scope="col">Dormitory</th>
        <th scope="col">latitude</th>
        <th scope="col">longitude</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td><%=  @hotel.name %></td>
        <td><%= @hotel.city.name %></td>
        <td><%=  @hotel.single_bedroom_num %></td>
        <td><%=  @hotel.double_bedroom_num %></td>
        <td><%=  @hotel.suite_room_num %></td>
        <td><%=  @hotel.dormitory_room_num %></td>\
        <td><%=  @hotel.latitude %></td>
        <td><%=  @hotel.longitude %></td>
      </tr>
    </tbody>
  </table>
</div>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
  function initMap(lat, lng) {
    var myCoords = new google.maps.LatLng(lat, lng);
    var mapOptions = {
      center: myCoords,
      zoom: 14
    };
    var map = new google.maps.Map(document.getElementById('map'), mapOptions);
    var marker = new google.maps.Marker({
      position: myCoords,
      map: map
    });
  }

  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
    {
      "lat": 37.3333945,
      "lng": -121.8806499,
      "picture": {
        "width":  32,
        "height": 32
      },
      "infowindow": "SJSU"
    }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });

</script>