config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "static_pages/home", to: "static_pages#home"
  get "static_pages/adminpage", to: "static_pages#adminpage"
  get 'search_hotels/show', to: "search_hotels#show"
  get "auth/:provider/callback", to: "sessions#create_from_socialmedia"
  get '/redirect', to: 'example#redirect', as: 'redirect'
  get '/callback', to: 'example#callback', as: 'callback'
  get '/calendars', to: 'example#calendars', as: 'calendars'
  get '/events/:calendar_id', to: 'example#events', as: 'events', calendar_id: /[^\/]+/
  post '/events/:calendar_id', to: 'example#new_event', as: 'new_event', calendar_id: /[^\/]+/
  get 'auth/failure', to: redirect('/')

  resources :users, only: [:new, :create]

  namespace :admin do
    resources :hotels
    resources :cities
    resources :rooms
  end

  resources :galleries, only: [:new, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :search_hotels, only: :show
  resources :bookings do
    get :client_bookings, on: :collection
    get :update_status, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">

</footer>

app/views/layouts/_header.html.erb
      <nav class="navbar navbar-expand-lg navbar-light bg-light mb-2">
      <a class="navbar-brand" href="#">Hotel Reservation System</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Gallery", galleries_path, class: "nav-link" %>
          </li>

          <% if current_user.present? %>

            <li class="nav-item">
              <%= link_to "Admin", static_pages_adminpage_path, class: "nav-link" if is_admin? %>
              <%= link_to "Welcome #{current_user.name}", root_path, class: "nav-link"  unless is_admin? %>
             </li>
             <li class="nav-item">
              <%= link_to "View my Bookings", bookings_path, class: "nav-link"  unless is_admin? %>
            </li>
            <li class="nav-item">
              <%= link_to "Signout", session_path(current_user), method: :delete, class: "nav-link" %>
            </li>

          <% else %>

            <li class="nav-item">
              <%= link_to "Signup", new_user_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Login", new_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign in with Facebook", "/auth/facebook" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign in with Google", "/auth/google_oauth2"%>
            </li>

          <% end %>

        </ul>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelRoomReservation | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>
    <%#= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+Rails.application.credentials.google_maps_api_key %>
    <%= include_gon %>
    <%= yield(:head_tags) %>
    </head>
  <body>

  <%= render 'layouts/header' %>
    <div class="container">
    <% if notice %>
      <%= notice %>
    <% end %>

    <% if alert %>
       <%= alert %>
    <% end %>

    <% if !flash.empty? %>
        <div id="flash">

          <% flash.keys.each do |f| %>
            <% @class = (f=="error")? "#{f} text-danger" : "#{f} text-success" %>
            <div class = "<%= @class %>" >
              <%= flash[f] %>
            </div>
          <% end %>
        </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>